name: Minecraft Server Workflow

on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  SERVER_JAR: paperclip.jar
  NGROK_AUTH_TOKEN: ${{ secrets.NGROK_AUTH_TOKEN }}

jobs:
  run-minecraft-server:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Download and configure PaperMC
        run: |
          wget https://api.papermc.io/v2/projects/paper/versions/1.19.3/builds/399/downloads/paper-1.19.3-399.jar -O $SERVER_JAR
          echo "eula=true" > eula.txt

      - name: Start Minecraft Server and ngrok
        run: |
          java -Xmx2G -Xms2G -jar $SERVER_JAR nogui & 
          wget https://bin.equinox.io/c/4VmDzA7iaHb/ngrok-stable-linux-amd64.zip -O ngrok.zip
          unzip ngrok.zip
          ./ngrok authtoken $NGROK_AUTH_TOKEN
          ./ngrok tcp 25565 --region=us > ngrok.log &
          sleep 10
          NGROK_URL=$(grep -o -E "tcp://(.+)" ngrok.log | sed "s/tcp:/https:/")
          if [ -n "$NGROK_URL" ]
          then
            echo "Minecraft server is running at: $NGROK_URL"
          else
            echo "Failed to start Minecraft server and ngrok"
            exit 1
          fi

      - name: Loop for 2 hours and save server data to GitHub
        if: success()
        run: |
          for i in {1..120}
          do
            sleep 60
            echo "Loop iteration $i"
            screen -S minecraft -X stuff "save-all$(printf '\r')"
            screen -S minecraft -X stuff "say Server data saved to GitHub$(printf '\r')"
            git add .
            git commit -m "Save server data to GitHub"
            git push
          done

      - name: Save server data to GitHub
        if: failure() || cancelled()
        uses: actions/github-script@v4
        with:
          script: |
            const message = `Minecraft server data not saved to GitHub due to ${github.event_name}`;
            const { context: { sha, repo: { owner, repo } } } = github;
            github.repos.createCommitComment({ owner, repo, sha, body: message });
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
