name: Minecraft Server Workflow

on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  SERVER_JAR: paperclip.jar
  NGROK_AUTH_TOKEN: ${{ secrets.NGROK_AUTH_TOKEN }}

jobs:
  run-minecraft-server:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Download and configure PaperMC
        run: |
          wget https://papermc.io/api/v2/projects/paper/versions/1.18.2/builds/1/downloads/paper-1.18.2-1.jar -O $SERVER_JAR
 -O $SERVER_JAR
          echo "eula=true" > eula.txt

      - name: Start Minecraft Server
        run: java -Xmx2G -Xms2G -jar $SERVER_JAR nogui

      - name: Download and configure ngrok
        run: |
          wget https://bin.equinox.io/c/4VmDzA7iaHb/ngrok-stable-linux-amd64.zip -O ngrok.zip
          unzip ngrok.zip
          ./ngrok authtoken $NGROK_AUTH_TOKEN

      - name: Start ngrok and forward Minecraft port
        run: |
          ./ngrok tcp 25565 --region=us > ngrok.log &
          sleep 10
          echo "Minecraft server is running at: $(grep -o -E "tcp://(.+)" ngrok.log | sed "s/tcp:/https:/")"

      - name: Print ngrok URL
        run: |
          echo "Minecraft server is running at: $(grep -o -E "tcp://(.+)" ngrok.log | sed "s/tcp:/https:/")"

      - name: Loop for 2 hours and save server data to GitHub
        run: |
          for i in {1..120}
          do
            sleep 60
            echo "Loop iteration $i"
            screen -S minecraft -X stuff "save-all$(printf '\r')"
            screen -S minecraft -X stuff "say Server data saved to GitHub$(printf '\r')"
            git add .
            git commit -m "Save server data to GitHub"
            git push
          done
